config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'time_sheets#index'
  resources :time_sheets
  match "time_sheets/:id/clock_out", to: 'time_sheets#clock_out', as: "clock_out", via: :patch

  # match "time_sheets/:id/clock_out", to: 'time_sheets#clock_out', as: "clock_out", via: :patch
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/time_sheet.rb
class TimeSheet < ApplicationRecord
  belongs_to :user

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :time_sheets
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/time_sheets_controller.rb
class TimeSheetsController < ApplicationController
  before_action :set_time_sheet, only: %i[ show edit update destroy clock_out ]

  # GET /time_sheets or /time_sheets.json
  def index
    @time_sheets = current_user.time_sheets.all
  end

  # GET /time_sheets/1 or /time_sheets/1.json
  def show
  end

  # GET /time_sheets/new
  def new
    @time_sheet = current_user.time_sheets.new
  end

  # GET /time_sheets/1/edit
  def edit
  end

  # POST /time_sheets or /time_sheets.json
  def create
    # byebug
    @time_sheet = current_user.time_sheets.new(clock_in: DateTime.now.localtime)

    respond_to do |format|
      if @time_sheet.save
        format.html { redirect_to @time_sheet, notice: "Time sheet was successfully created." }
        format.json { render :show, status: :created, location: @time_sheet }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @time_sheet.errors, status: :unprocessable_entity }
      end
    end
  end

  def clock_out
    respond_to do |format|
      if @time_sheet.update(clock_out: DateTime.now.localtime)
        format.html { redirect_to @time_sheet, notice: "Time sheet was clocked out." }
        format.json { render :show, status: :ok, location: @time_sheet }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @time_sheet.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /time_sheets/1 or /time_sheets/1.json
  def update
    respond_to do |format|
      if @time_sheet.update(time_sheet_params)
        format.html { redirect_to @time_sheet, notice: "Time sheet was successfully updated." }
        format.json { render :show, status: :ok, location: @time_sheet }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @time_sheet.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /time_sheets/1 or /time_sheets/1.json
  def destroy
    @time_sheet.destroy
    respond_to do |format|
      format.html { redirect_to time_sheets_url, notice: "Time sheet was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_time_sheet
      @time_sheet = current_user.time_sheets.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def time_sheet_params
      params.require(:time_sheet).permit(:clock_in, :clock_out)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/time_sheets_helper.rb
module TimeSheetsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Testtime</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div id="container">
      <div id="user_nav">
        <% if user_signed_in? %>
          Logged in as <strong><%= current_user.email %></strong>.
          <%= link_to 'Edit profile', edit_user_registration_path %> |
          <%= link_to "Logout", destroy_user_session_path, method: :delete %>
        <% else %>
          <%= link_to "Sign up", new_user_registration_path %> |
          <%= link_to "Login", new_user_session_path %>
        <% end %>
      </div>

      <% flash.each do |name, msg| %>
        <%= content_tag :div, msg, id: "flash_#{name}" %>
      <% end %>

    </div>
    <%= yield %>

  </body>
</html>

app/views/time_sheets/_form.html.erb
<%= form_with(model: time_sheet) do |form| %>
  <% if time_sheet.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(time_sheet.errors.count, "error") %> prohibited this time_sheet from being saved:</h2>

      <ul>
        <% time_sheet.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>



  <% unless time_sheet.clock_in.nil? %>
    <div class="field">
      <%= form.label :clock_in %>
      <%= form.datetime_select :clock_in %>
    </div>
  <% end %>

  <% unless time_sheet.clock_out.nil? %>

    <div class="field">
      <%= form.label :clock_out %>
      <%= form.datetime_select :clock_out %>
    </div>
  <% end %>


  <div class="actions">
    <%= form.submit "Clock In" %>
  </div>
<% end %>

app/views/time_sheets/edit.html.erb
<h1>Editing Time Sheet</h1>

<%= render 'form', time_sheet: @time_sheet %>

<%= link_to 'Show', @time_sheet %> |
<%= link_to 'Back', time_sheets_path %>

app/views/time_sheets/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Time Sheets</h1>

<table>
  <thead>
    <tr>
      <th>Clock in</th>
      <th>Started</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @time_sheets.each do |time_sheet| %>
      <tr>
        <td><%= time_sheet.clock_in %></td>

        <td><%= link_to 'Show', time_sheet %></td>
        <td><%= link_to 'Edit', edit_time_sheet_path(time_sheet), id: "edit-link-show" %></td>
        <td><%= link_to 'Destroy', time_sheet, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% if time_sheet.clock_out.nil? %>
          <td><%= form_for time_sheet, url: clock_out_path(time_sheet) do |f| %>
              <%= f.submit "Clock out"  %></td>
          <% end %>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Time Sheet', new_time_sheet_path %>

app/views/time_sheets/new.html.erb
<h1>New Time Sheet</h1>

<%= render 'form', time_sheet: @time_sheet %>

<%= link_to 'Back', time_sheets_path %>

app/views/time_sheets/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Clock in:</strong>
  <%= @time_sheet.clock_in %>
</p>

<p>
  <% unless @time_sheet.clock_out.nil? %>
    <p>
      <strong>Clock out:</strong>
      <%= @time_sheet.clock_out %>
    </p>
    <strong>Total time:</strong>
    <% ActiveSupport::Duration.build(@time_sheet.clock_out - @time_sheet.clock_in).parts.each_pair do |k,v| %>
      <%= k %>: <%= v %>|
    <% end %>
    </p>
  <% end %>

<%= link_to 'Edit', edit_time_sheet_path(@time_sheet), class: "edit-link-show" %> |
<%= link_to 'Back', time_sheets_path %>